### ISSUE TITLE
Allow the chunk to be optional by chunk or verse

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#264]
## User Story
In order to reflect the fact that translators may do more or less that a uniform chunk, we need the ability also auto-increment by verse number.

## Definition of Done

- [ ] Provide a toggle option to change the counter from Chunk by Chunk to Verse by Verse.

AND/OR

- [ ] Allow the user to enter in a number in the "next increment" field

**Comment by PurpleGuitar** [comment]
## To-Do List

- [ ] Investigate how to get the maximum verse for a chapter
    - Is it in the file we're loading now?
    - If not, is it in another file we already have?
- [ ] Create preference to allow picking by verse instead of chapter
- [ ] When preference is set, load picker with verses instead of chunks
- [ ] Unit testing
